defmodule Tunez.Repo.Migrations.CreateAlbums do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:albums, primary_key: false) do
      add :artist_id,
          references(:artists, column: :id, name: "albums_artist_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :cover_image_url, :text
      add :year_released, :bigint, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:albums, "albums_artist_id_fkey")

    drop table(:albums)
  end
end